export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const MODE_MEETING_HOST = 'MODE_MEETING_HOST';
export const MODE_MEETING_GUEST = 'MODE_MEETING_GUEST';

export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const JOIN_MEETING_SUCCESS = 'JOIN_MEETING_SUCCESS';

export const UPDATE_MEETING_MEMBER = 'UPDATE_MEETING_MEMBER';
export const RECEIVE_MEETING_CALL = 'RECEIVE_MEETING_CALL';
export const SENDING_MEETING_CALL = 'SENDING_MEETING_CALL';
export const ACCEPTING_MEETING_CALL = 'ACCEPTING_MEETING_CALL';
export const RECEIVE_MEETING_CALLER_INFO = 'RECEIVE_MEETING_CALLER_INFO';
export const RECEIVE_MEETING_CALLER_STREAM = 'RECEIVE_MEETING_CALLER_STREAM';

export const UPDATE_MEETING_START = 'UPDATE_MEETING_START';
export const UPDATE_MEETING_STOP = 'UPDATE_MEETING_STOP';
export const UPDATE_MEETING_RECORDER = 'UPDATE_MEETING_RECORDER';

export const RECEIVE_MEETING_MEMBER = 'RECEIVE_MEETING_MEMBER';
export const RECEIVE_MEETING_STARTTIME = 'RECEIVE_MEETING_STARTTIME';
export const RECEIVE_MEETING_ENDTIME = 'RECEIVE_MEETING_ENDTIME';
export const RECEIVE_MYSTREAM = 'RECEIVE_MYSTREAM';
