export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const MODE_MEETING_HOST = 'MODE_MEETING_HOST';
export const MODE_MEETING_GUEST = 'MODE_MEETING_GUEST';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const JOIN_MEETING_SUCCESS = 'JOIN_MEETING_SUCCESS';
export const RECEIVE_SOCKET_MESSAGE = 'RECEIVE_SOCKET_MESSAGE';
export const RECEIVE_MYSTREAM = 'RECEIVE_MYSTREAM';
