export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const MODE_MEETING_NEW = 'MODE_MEETING_NEW';
export const MODE_MEETING_JOIN = 'MODE_MEETING_JOIN';
export const NEW_MEETING_SUCCESS = 'NEW_MEETING_SUCCESS';
